apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app
  labels:
    app: starbucks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starbucks-app
  template:
    metadata:
      labels:
        app: starbucks-app
    spec:
      containers:
      - name: starbucks-app
        image: divyasatpute/starbucks:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: starbucks-app-service
spec:
  selector:
    app: starbucks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      #NodePort: 30000  # Optional: Specify a port between 30000-32767
  type: LoadBalancer
